# Site settings
title: Andrea Fontalvo
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Andrea Fontalvo
user_description: Tech and photographt enthusiast
user_title: Electronics Engineer
email: mauriurraco@gmail.com
# twitter_username: lorem_ipsum
github_username:  andreafontalvo
instagram_username: andreacfontalvo
# linkedin_username: afontalvoechavez
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
